services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/db:/var/lib/mysql
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - MYSQL_DATABASE_URL=mysql+pymysql://myuser:mypassword@db:3306/todos
    volumes:
      - .:/app
volumes:
  mysql_data:
