services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'todo_database'
      MYSQL_ROOT_PASSWORD: 'roopass'
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/db:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - local-net
  app:
    links:
      - db
    build: ./docker/api
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    networks:
      - local-net
    environment:
      MYSQL_DATABASE: 'todo_database'
      MYSQL_ROOT_PASSWORD: 'roopass'
      MYSQL_HOST: db

networks:
  local-net:
    driver: bridge
